version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - app/.env

  app:
    build: .
    command: /./wait-for-postgres.sh
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - app/.env
